### ISSUE TITLE
Precompiled Binaries for Python Package

### ISSUE THREAD

**Issue by sharora** [lunathanael/botris-interface#3]
### Proposed new feature or change:

Would it be possible to distribute precompiled binaries via PyPI? Currently when I try to install the dev version of the package, it tries to build the C++ extension locally and it took a while to get the compiler version, cmake version, and python version correct for the build to even start (and its still failing for me).

It might be easier for people who want to use this library in the future if they didn't have to build from scratch to install and they could just install a pre compiled binary for their architecture.

**Comment by lunathanael** [comment]
Welcome and thank you for using botris-interface!

This is a great idea, you can track progress via the project. Currently waiting on bug fixes from a dependency repository: shakkar23/ShakTrisLib#1

**Comment by lunathanael** [comment]
Please test the pre-release at [pypi](https://pypi.org/project/botris-interface/0.2.0.dev2/), or `pip install botris-interface==0.2.0.dev2`.

v0.2.0.dev2: https://github.com/lunathanael/botris-interface/commit/3375f69cbc5e499cedaed7e02af36fa91ff4404e
