### ISSUE TITLE
Zero Copy View of CBoard type

### ISSUE THREAD

**Issue by sharora** [lunathanael/botris-interface#6]
### Proposed new feature or change:

After profiling my first bot it seems that about 15% of total time comes from taking a `botris._core.Game` state and extracting the board as as a numpy array through `np.array(gs.board.board, dtype=np.uint32)`.

From my understanding this first copies the underlying `std::array` to a python list and then copies a second time to produce an array in memory with the correct type (in this case uint32 to correctly represent the cells on the tetris board).

I thought that we might be able to use a feature from [nanobind](https://nanobind.readthedocs.io/en/latest/ndarray.html), the current binding library, that allows for zero copy exchange between the two languages. 

I implemented this feature locally by adding the following to `board.cpp` in `_core/`:

```
        .def("numpy_view", [](Board &self) {
            size_t shape[1] = {Board::width}; 
            return nb::ndarray<nb::numpy, uint32_t, nb::shape<1>>(
                /* data = */ self.board.data(),
                /* ndim = */ 1,
                /* shape pointer = */ shape,
                /* owner = */ nb::handle());
        }, nb::rv_policy::reference_internal)
```
This closely follows the examples provided in the nanobind documentation. I have verified that the returned numpy array provides read/write access to the underlying memory used to store the board. However I am unsure if this is leading to any noticeable speedup in my own testing (I haven't been able to measure much of a difference).

If anybody else could reproduce my results that would be nice. Also any feedback on any potential mistakes I have made would be appreciated.

**Comment by lunathanael** [comment]
Thanks for the issue @sharora,

Currently, the reasoning for using a copy reference was to prevent any memory corruption or data invalidation that might occur from delete operations. Such, as to eliminate any overhead from pre-converting to an NDArray when unnecessary. 

The solution you have provided was certainly considered but not seriously tested. I will do some similar local testing, however, in the meantime you can:

- Create a pull request with the suggested changes and testing benchmark results.
- Consider alternatives to creating a numpy array.

Thank you!

**Comment by lunathanael** [comment]
Initial testing seems to have proved little to no improvement, with suggestions for downgrading performance.

This seems to suggest that either perhaps a parameter or two is set incorrectly or that such optimizations are infeasible and inefficient.

For code referencing testing check 4aebbfaaba8696a8d239459da17f46393d171a06, note that while undocumented, both `nb::rv_policy::reference` and `nb::rv_policy::reference_internal` were tested. Of the two `reference_internal`, seemed to perform slightly better but with the cons of the dangerous nature as well.

Note that all testing was very simple, insignificant, and local to a single computer. Feel free to do more well based testing!

Thank you!
